wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.24
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.10
    t:
      1:
      - 1
      - 5
      4: 3.7.10
      5: 0.10.24
      8:
      - 5
config_file:
  desc: null
  value: configs/wsod/wsod_faster_r50_fpn_1x_voc.py
logfile:
  desc: null
  value: /data1/dataset/dy/work_dirs/wsod_faster_voc07/20210401_101924.log
strong_label_percentage:
  desc: null
  value: 0.11055694098088113
time:
  desc: null
  value: '20210401_101924'
work_dir:
  desc: null
  value: /data1/dataset/dy/work_dirs/wsod_faster_voc07
