wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.24
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.10
    t:
      1:
      - 1
      - 5
      4: 3.7.10
      5: 0.10.24
      8:
      - 5
logfile:
  desc: null
  value: /data1/dataset/dy/work_dirs/faster_rcnn_voc/20210401_100901.log
